--drop table if exists question
--
--drop table if exists question_category
--
--drop table if exists question_like
--
create table if not exists question (
   question_id bigint generated by default as identity,
    created_at timestamp,
    last_modified_at timestamp,
    content varchar(255) not null,
    question_answer_status varchar(21) not null,
    question_open_status varchar(20) not null,
    title varchar(255) not null,
    primary key (question_id)
);

create table if not exists question_category (
    question_question_id bigint not null,
    category varchar(255) not null
);

alter table question_category {
   add constraint FK5gjf122b4kv9jdqbyqi2tehoi
   foreign key (question_question_id)
   references question
};
