spring:
  h2:
    console:
      enabled: true
      path: /h2
  datasource:
    url: jdbc:h2:mem:test
<<<<<<< HEAD
#  sql:
#    init:
#      schema-locations: classpath*:h2/schema.sql
#      data-locations: classpath*:h2/data.sql
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
=======
  sql:
    init:
      schema-locations: classpath*:h2/schema.sql
      data-locations: classpath*:h2/data.sql
  jpa:
    hibernate:
      ddl-auto: update  # (1) 스키마 자동 생성
    show-sql: true      # (2) SQL 쿼리 출력
>>>>>>> 1ac39782a8c0df2fc1e6fd53987bc9daf1cca345
    properties:
      hibernate:
        format_sql: true
logging:
  level:
    org:
      springframework:
        orm:
          jpa: DEBUG
